version: 2
updates:
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "edgarrmondragon"
