version: 2
updates:
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "edgarrmondragon"

# Template
  - package-ecosystem: pip
    directory: "/src"
    schedule:
      interval: weekly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
  - package-ecosystem: pip
    directory: "/src/[% if repository_provider == 'github.com' %].github[% endif %]/workflows"
    schedule:
      interval: weekly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
  - package-ecosystem: pip
    directory: "/src/"
    schedule:
      interval: weekly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
