version: 2
updates:
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
    groups:
      ci-dependencies:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - "edgarrmondragon"
    groups:
      ci-dependencies:
        update-types:
          - "patch"
          - "minor"

# Template
  - package-ecosystem: pip
    directory: "/src"
    schedule:
      interval: monthly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
  - package-ecosystem: pip
    directory: "/src/[% if repository_provider == 'github.com' %].github[% endif %]/workflows"
    schedule:
      interval: monthly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
    groups:
      CI:
        update-types:
          - "patch"
          - "minor"
