version: 2
updates:
  - package-ecosystem: pip
    directory: "/.github/workflows/tools"
    schedule:
      interval: monthly
    reviewers:
      - "edgarrmondragon"
    labels:
      - "dependencies"
    groups:
      ci-tools:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - "edgarrmondragon"
    groups:
      actions:
        patterns:
          - "*"
