ci:
  autofix_prs: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-json
    exclude: "src\\/.*\\.vscode.*\\/.*.json"
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.2
  hooks:
  - id: check-dependabot
  - id: check-github-workflows
