ci:
  autofix_prs: false
  skip:
  - check-dependabot

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
    exclude: "src\\/.*\\.vscode.*\\/.*.json"
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.4
  hooks:
  - id: check-dependabot
  - id: check-github-workflows
