name: Test template output

on:
  pull_request:
    paths:
    - src/**
    - noxfile.py
    - .github/workflows/test.yml
    - .github/workflows/constraints.txt
    - copier.yml
  push:
    branches:
    - 'main'
    paths:
    - src/**
    - noxfile.py
    - .github/workflows/test.yml
    - .github/workflows/constraints.txt
    - copier.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linting:
    env:
      FORCE_COLOR: "1"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        visibility: ["private", "public"]
        stream_type: ["REST", "GraphQL"]
        auth_method: ["API Key", "Bearer Token", "Basic Auth", "OAuth2", "JWT", "Custom or N/A"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: astral-sh/setup-uv@v3

    - name: Install copier
      env:
        UV_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
      run: |
        uv tool install copier
        copier --version

    - name: Install Hatch
      env:
        UV_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
      run: |
        uv tool install hatch
        hatch --version

    - name: Install Nox
      env:
        UV_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
      run: |
        uv tool install nox
        nox --version

    - name: Install pre-commit
      env:
        UV_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt
      run: |
        uv tool install pre-commit --with pre-commit-uv
        pre-commit --version

    - name: Install dependencies
      run: >
        nox
        --install-only
        -s "lint-${{ matrix.python-version }}(visibility='${{ matrix.visibility }}', auth_method='${{ matrix.auth_method }}', stream_type='${{ matrix.stream_type }}')"

    - name: Run Nox
      env:
        PYTHONWARNINGS: "all,error::DeprecationWarning,ignore::DeprecationWarning:setuptools_scm._get_version_impl"
      run: >
        nox
        --reuse-existing-virtualenvs
        --no-install
        -s "lint-${{ matrix.python-version }}(visibility='${{ matrix.visibility }}', auth_method='${{ matrix.auth_method }}', stream_type='${{ matrix.stream_type }}')"
