name: Test template output

on:
  pull_request:
    paths:
    - src/**
    - noxfile.py
    - .github/workflows/test.yml
    - copier.yml
  push:
    branches:
    - 'main'
    paths:
    - src/**
    - noxfile.py
    - .github/workflows/test.yml
    - copier.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  # renovate: datasource=pypi depName=copier
  COPIER_VERSION: 9.6.0
  # renovate: datasource=pypi depName=hatch
  HATCH_VERSION: 1.14.0
  # renovate: datasource=pypi depName=nox
  NOX_VERSION: 2024.10.9
  # renovate: datasource=pypi depName=pre-commit
  PRE_COMMIT_VERSION: 4.0.1
  # renovate: datasource=pypi depName=pre-commit-uv
  PRE_COMMIT_UV_VERSION: 4.1.4
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.6.9

jobs:
  linting:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        visibility: ["private", "public"]
        stream_type: ["REST", "GraphQL"]
        auth_method:
        - "API Key"
        - "Bearer Token"
        - "Basic Auth"
        - "OAuth2"
        - "JWT"
        - "Custom or N/A"

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: 3.x

    - uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
      with:
        version: ${{ env.UV_VERSION }}

    - name: Install copier
      run: |
        uv tool install --with copier==${{ env.COPIER_VERSION }} copier
        copier --version

    - name: Install Hatch
      run: |
        uv tool install --with hatch==${{ env.HATCH_VERSION }} hatch
        hatch --version

    - name: Install Nox
      run: |
        uv tool install --with nox==${{ env.NOX_VERSION }} nox
        nox --version

    - name: Install pre-commit
      run: |
        uv tool install --with pre-commit-uv==${{ env.PRE_COMMIT_UV_VERSION }} --with pre-commit==${{ env.PRE_COMMIT_VERSION }} pre-commit
        pre-commit --version

    - name: Install dependencies
      run: >
        nox
        --install-only
        -s "lint(visibility='${{ matrix.visibility }}', auth_method='${{ matrix.auth_method }}', stream_type='${{ matrix.stream_type }}')"

    - name: Run Nox
      env:
        PYTHONWARNINGS: "all,error::DeprecationWarning,ignore::DeprecationWarning:setuptools_scm._get_version_impl"
      run: >
        nox
        --reuse-existing-virtualenvs
        --no-install
        -s "lint(visibility='${{ matrix.visibility }}', auth_method='${{ matrix.auth_method }}', stream_type='${{ matrix.stream_type }}')"
