name: Test template output

on:
  pull_request:
    paths:
    - src/**
    - noxfile.py
    - .github/workflows/test.yml
    - .github/workflows/tools/**
    - copier.yml
  push:
    branches:
    - 'main'
    paths:
    - src/**
    - noxfile.py
    - .github/workflows/test.yml
    - .github/workflows/tools/**
    - copier.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  REQUIREMENTS_DIR: ${{ github.workspace }}/.github/workflows/tools

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        visibility: ["private", "public"]
        stream_type: ["REST", "GraphQL"]
        auth_method:
        - "API Key"
        - "Bearer Token"
        - "Basic Auth"
        - "OAuth2"
        - "JWT"
        - "Custom or N/A"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - uses: astral-sh/setup-uv@v3

    - name: Install copier
      run: |
        uv tool install --with-requirements ${{ env.REQUIREMENTS_DIR }}/copier-requirements.txt copier
        copier --version

    - name: Install Hatch
      run: |
        uv tool install --with-requirements ${{ env.REQUIREMENTS_DIR }}/hatch-requirements.txt hatch
        hatch --version

    - name: Install Nox
      run: |
        uv tool install --with-requirements ${{ env.REQUIREMENTS_DIR }}/nox-requirements.txt nox
        nox --version

    - name: Install pre-commit
      run: |
        uv tool install pre-commit --with-requirements ${{ env.REQUIREMENTS_DIR }}/pre-commit-requirements.txt
        pre-commit --version

    - name: Install dependencies
      run: >
        nox
        --install-only
        -s "lint(visibility='${{ matrix.visibility }}', auth_method='${{ matrix.auth_method }}', stream_type='${{ matrix.stream_type }}')"

    - name: Run Nox
      env:
        PYTHONWARNINGS: "all,error::DeprecationWarning,ignore::DeprecationWarning:setuptools_scm._get_version_impl"
      run: >
        nox
        --reuse-existing-virtualenvs
        --no-install
        -s "lint(visibility='${{ matrix.visibility }}', auth_method='${{ matrix.auth_method }}', stream_type='${{ matrix.stream_type }}')"
